"""Generate operation documentation and schemas from the actual service contract."""

import argparse
import json
from pathlib import Path

from tpac_studio.service import Studio


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if committed references differ")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    studio = Studio()
    try:
        schemas = studio.schemas()
    finally:
        studio.close()
    lines = [
        "# Operation reference",
        "",
        "Generated by `python tools/generate_reference.py`; do not edit manually.",
        "",
        "Operations are shared by Python, JSON CLI and MCP. See [API semantics](api.md).",
        "",
    ]
    for name, schema in sorted(schemas["operations"].items()):
        lines += [
            f"## `{name}`",
            "",
            schema["description"],
            "",
            "```json",
            json.dumps(schema, indent=2, sort_keys=True),
            "```",
            "",
        ]
    files = {
        root / "docs/api-reference.md": "\n".join(lines),
        root / "src/tpac_studio/schemas/operations.json": json.dumps(
            schemas, indent=2, sort_keys=True
        )
        + "\n",
    }
    stale = []
    for path, contents in files.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf8") != contents:
                stale.append(str(path.relative_to(root)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents, encoding="utf8", newline="\n")
    if stale:
        raise SystemExit("Regenerate stale references: " + ", ".join(stale))


if __name__ == "__main__":
    main()
